version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: lunara_postgres
    environment:
      POSTGRES_USER: Owen
      POSTGRES_PASSWORD: omni
      POSTGRES_DB: lunara_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 