spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /api

app:
  jwt:
    # Generate your own secret key and replace this placeholder
    secret: your_jwt_secret_key_here
    expiration: 86400000 # 1 day
    refresh-expiration: 604800000 # 7 days

# Note: This is an example configuration file. 
# Copy this file to application.yml and replace the placeholder values with your actual configuration. 