spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/lunara_db
    username: Owen
    password: omni
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 24 hours in milliseconds
    refresh-token:
      expiration: 604800000 # 7 days in milliseconds

# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api
  cors:
    allowed-origins: http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  web:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true 